const REFETECH_CHATS = "refetch_chats";
const NEW_REQUEST = "new_request";
const NEW_MESSAGE_ALERT = "new_message_alert";
const NEW_MESSAGE = "NEW_MESSAGE";
const IS_TYPING = "Is_typing";
const STOP_TYPING = "Stop_Typing";
const CHAT_JOINED = "CHATJOINED";
const CHAT_LEFT = "CHATLEFT";
const I_AM_ONLINE = "iamonline";
const ONLINE_USER = "onlineUser";
const I_AM_OFFLINE = "iamoffline";
const InitialUsersStatus = "initialUsersStatus";
const USER_STATUS_CHANGE = "userStatusChange";
const NEW_GROUP_MESSAGE = "NEW_GROUP_MESSAGE";
const MARK_MESSAGES_READ = "MARK_MESSAGES_READ";
const NEW_GROUP_MESSAGE_ALERT = "NEW_GROUP_MESSAGE_ALERT"

const MARK_GROUP_MESSAGES_READ = "MARK_GROUP_MESSAGES_READ"

export {
  NEW_GROUP_MESSAGE_ALERT,
  MARK_GROUP_MESSAGES_READ,
  InitialUsersStatus,
  MARK_MESSAGES_READ,
  NEW_GROUP_MESSAGE,
  USER_STATUS_CHANGE,
  ONLINE_USER,
  I_AM_OFFLINE,
  I_AM_ONLINE,
  CHAT_JOINED,
  CHAT_LEFT,
  IS_TYPING,
  STOP_TYPING,
  NEW_MESSAGE,
  REFETECH_CHATS,
  NEW_REQUEST,
  NEW_MESSAGE_ALERT,
};
